service: audit

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip:true

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:Query
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::cyberark-audit-content/*"
functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'